language: r
sudo: required
cache: packages

warnings_are_errors: true

r_packages:
- GGally
- ggplot2
- knitr
- rmarkdown
- scales
- stats
- tidyr
- utils

bioc_packages:
- Biobase
- DESeq2
- edgeR
- SummarizedExperiment

install:
- Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
