language: R
sudo: false
cache: packages
r:
    - devel

warnings_are_errors: true
bioc_required: true
bioc_use_devel: true

r_packages:
    - GGally
    - ggplot2
    - knitr
    - rmarkdown
    - scales
    - stats
    - tidyr
    - utils

bioc_packages:
    - Biobase
    - DESeq2
    - edgeR
    - SummarizedExperiment

install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("knitr", repos = "http://cran.rstudio.com")'
